[build]
  command = "npm install && npm install -D vite@latest && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE = "true"  # This helps Vite detect it's in a build environment
  CI = "false"   # Disable CI to prevent any CI-specific behavior
  NODE_OPTIONS = "--max_old_space_size=4096"  # Increase memory limit for build
  PATH = "/opt/buildhome/.nvm/versions/node/v20.19.4/bin:/opt/buildhome/.yarn/bin:/opt/buildhome/.config/yarn/global/node_modules/.bin:/opt/buildhome/.nvm/versions/node/v20.19.4/bin:/opt/buildhome/.yarn/bin:/opt/buildhome/.config/yarn/global/node_modules/.bin:/opt/buildhome/.cabal/bin:/opt/buildhome/.ghcup/bin:/opt/buildhome/.cargo/bin:/opt/buildhome/.local/bin:/opt/buildhome/bin:/opt/buildhome/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# No plugins needed for Vite
# Remove any automatic Next.js plugin if added by Netlify UI
