[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  # Explicitly disable all plugins
  plugins = []

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "development"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE = "true"
  CI = "false"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_CONFIG_PRODUCTION = "false"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# No plugins needed for Vite
# Remove any automatic Next.js plugin if added by Netlify UI
