[build]
  command = "npm install -g vite && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE = "true"  # This helps Vite detect it's in a build environment

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# No plugins needed for Vite
# Remove any automatic Next.js plugin if added by Netlify UI
