[build]
  command = "npm install && npx vite build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE = "true"  # This helps Vite detect it's in a build environment
  CI = "false"   # Disable CI to prevent any CI-specific behavior
  NODE_OPTIONS = "--max_old_space_size=4096"  # Increase memory limit for build

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# No plugins needed for Vite
# Remove any automatic Next.js plugin if added by Netlify UI
